#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Bdsl\OnlyOne\Start;
use Bdsl\OnlyOne\Release;
use Symfony\Component\Console\Application;

$application = new Application('Only one');
$application->add(new Start());
$application->add(new Release());

$application->run();