#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Bdsl\OnlyOne\Start;
use Symfony\Component\Console\Application;

$application = new Application('Only one');
$command = new Start();

$application->add($command);

$application->run();